---
examples_limit: null #  limit tp num of processed examples - cut off all above
out_dir: ./dataset/tfrecords # output dir
base_input_dir: /home/ronen/PycharmProjects/cocod_shapes_dataset/dataset #/home/ronen/fiftyone/coco-2017/validation/data # datasets/coco2012/images
input_annotations_file: annotations.json # /home/ronen/fiftyone/coco-2017/validation/labels.json # datasets/coco2012/

splits:
  - train
  - valid
  - test

classes_name_file:  /home/ronen/fiftyone/coco-2017/coco.names
optimal_file_size: 104857600 # optimal tfrec file size. Split a larger dataset
